### ISSUE TITLE
It is not possible to create account if Identity attributes contain special characters

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-browser-wallet#483] opened 2024-07-26 13:18 UTC
**To reproduce:**

1. Create identity with name that contains one of Danish characters æ ø å. 
2. Try to create account with that identity.

**Result:**

Runtime error.

**Expected:**

It should be possible to create account.

**Workaround:**

There is no workaround in BW, one could recover in CryptoX and then create account.

**Note:**

This issue seems to be introduced with the latest release 1.6.0 as I was not able to reproduce it in 1.5.2.

Same goes for characters in German like Ü.

<img src="https://uploads.linear.app/430cc2b6-6b19-45f6-b7f0-6a0093e10c15/e4bf1b7d-96b7-499a-8ebf-5485f27a998d/b5168efd-1c46-4144-9064-1fb0ea54bd9c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzQzMGNjMmI2LTZiMTktNDVmNi1iN2YwLTZhMDA5M2UxMGMxNS9lNGJmMWI3ZC05NmI3LTQ5OWEtOGViZi01NDg1ZjI3YTk5OGQvYjUxNjhlZmQtMWM0Ni00MTQ0LTkwNjQtMWZiMGVhNTRiZDljIiwiaWF0IjoxNzIyMDAwMDY2LCJleHAiOjMzMjkyNTYwMDY2fQ.l76acWvEWPwwfaI2fgXZcvQtQrvy0XcW8xk38XiSJds " alt="image.png" width="552" height="895" />

**Comment by limemloh** [comment] 2024-08-07 12:21
This is caused by a bug in `@concordium/web-sdk`<br>[PR with fix can be found here](https://github.com/Concordium/concordium-node-sdk-js/pull/381)<br><br>When this fix is released in `@concordium/web-sdk`, a patch will be released for the browser wallet.

**Closed** 2024-08-07 17:44 UTC
